### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by dmke**
This fixes the FileInfo.modTime issue described in #10

### CODE REVIEW

**Comment by dmke** [comment]
Hm. Somehow, Github thinks I wanted to include all the commits after 2a2758f in this PR...

Anyway, this now includes the following improvements:

1. 3f528f8 takes a bit more care when generating the output (smaller diff after running gofmt on the generated file)
2. 20ab711 adds a `-width` flag to adjust the blockwidth (instead of using a static value of 12 byte values per line). I tried to avoid a global variable, but I still don't understand how the `template/text` works... Feel free to leave this out
3. 94f9a8d adds a `-fmt` CLI flag to run the generated output through `gofmt`'s formatting code

I've also included some sample test files an extended the test suite.

**Comment by omeid** [comment]
Thanks for this @dmke! I will review this later today.

**Comment by dmke** [comment]
I've now also added a fix for the `-declare` flag in `9b14597`, and improved the wording in the `README.md` a bit. Hope you don't mind :-)

**Comment by omeid** [comment]
This all looks super good. I will test it once I get some time later today and will merge it in.
Thanks again!

**Pull request merged**
